# Generated by Django 4.1 on 2023-01-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=150)),
                ('optionA', models.CharField(default='', max_length=28)),
                ('optionB', models.CharField(default='', max_length=28)),
                ('optionC', models.CharField(default='', max_length=28)),
                ('optionD', models.CharField(default='', max_length=28)),
                ('answer', models.CharField(default='', max_length=28)),
                ('topic', models.ManyToManyField(blank=True, to='java.topic')),
            ],
        ),
    ]
